version: "4.23"

services:
    # php service =====================
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=APP_ENV
        working_dir: /var/www/link-harvester-app
        volumes:
            - /Applications/XAMPP/xamppfiles/htdocs/link-harvester-app:/var/www/link-harvester-app
        ports:
            - 8000:8000
        depends_on: 
            - database
            - adminer

    # mysql database service =====================
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USERNAME=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db-data: ~
